import ContactPage from "./page";

export const metadata = {
  title: "Contact Us | Upteky",
  description: "Connect with Upteky for cutting-edge AI solutions, business inquiries, partnerships, and collaborations. We're here to help your business grow through intelligent automation.",
keywords: [
  "Upteky",
  "Contact Upteky",
  "AI solutions",
  "AI consulting services",
  "AI company India",
  "AI company Ahmedabad",
  "AI automation",
  "AI development agency",
  "custom AI solutions",
  "AI chatbot development",
  "AI SaaS company",
  "AI product development",
  "machine learning services",
  "ML and AI company",
  "deep learning solutions",
  "NLP development services",
  "contact AI company",
  "AI app development",
  "artificial intelligence services",
  "intelligent automation solutions",
  "business automation India",
  "AI software development",
  "enterprise AI integration",
  "data science services",
  "contact form AI company",
  "AI partnerships India",
  "Upteky Ahmedabad",
  "AI project consultation",
  "smart tech solutions",
  "hire AI developers",
  "AI innovation partner",
  "future of AI India",
  "AI solutions for startups",
  "custom AI bots",
  "AI tools for business",
  "contact tech company",
  "get in touch with Upteky",
  "AI engineering team",
  "intelligent tech services",
  "collaborate with AI experts",
  "digital transformation with AI",
  "AI services Gujarat",
  "AI agency India",
  "reach Upteky",
  "AI strategy consultation",
  "automated workflow AI",
  "AI solution provider",
  "B2B AI company",
  "contact intelligent automation firm",
  "AI-driven product company"
],
  authors: [{ name: "Upteky", url: "https://upteky.com" }],
  metadataBase: new URL("https://upteky.com"),
  openGraph: {
    title: "Contact Us | Upteky",
    description: "Have questions or want to partner with us? Reach out via our contact form or visit our office in Ahmedabad. We're ready to transform your ideas into intelligent solutions.",
    url: "https://upteky.com/contact",
    siteName: "Upteky",
    images: [
      {
        url: "/assets/Upteky Logo.png",
        width: 1200,
        height: 630,
        alt: "Upteky - AI Automation",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Contact Us | Upteky",
    description: "Fill out our form to reach Upteky. Let’s build the future of AI together.",
    images: ["/assets/Upteky Logo.png"],
  },
};

export default function Page() {
  return <ContactPage />;
}
